//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTeamManager.Model.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ManagerComment
    {
        public System.Guid Id { get; set; }
        [DisplayName("First Name")]
        [Required(ErrorMessage = "First Name is required.")]
        [StringLength(50, ErrorMessage = "First Name cannot be longer than 50 characters.")]
        public string FirstName { get; set; }
        [DisplayName("Last Name")]
        [Required(ErrorMessage = "Last Name is required.")]
        public string LastName { get; set; }
        [StringLength(50, ErrorMessage = "Last Name cannot be longer than 50 characters.")]
        [DisplayName("Manager Name")]
        public string FullName => FirstName + " " + LastName;
        [DisplayName("Employee Name")]
        [Required(ErrorMessage = "Employee Name is required.")]
        public System.Guid ProjectTaskId { get; set; }
        [DisplayName("Comment")]
        [Required(ErrorMessage = "Comment is required.")]
        public string Comments { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime InsAt { get; set; }
        public string InsBy { get; set; }
        public System.DateTime UpdAt { get; set; }
        public string UpdBy { get; set; }
        public virtual ProjectTask ProjectTask { get; set; }
    }
}
