//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTeamManager.Model.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ProjectTask : IValidatableObject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectTask()
        {
            this.ManagerComments = new HashSet<ManagerComment>();
        }
    
        public System.Guid Id { get; set; }
        [DisplayName("Employee Name")]
        [Required(ErrorMessage = "Employee Name is required.")]
        public System.Guid EmployeeId { get; set; }
        [DisplayName("Task Start Date")]
        [Required(ErrorMessage = "Task Start Date is required.")]
        [Editable(false)]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime TaskStartDate { get; set; }
        [DisplayName("Task End Date")]
        [Required(ErrorMessage = "Task End Date is required.")]
        [Editable(false)]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime TaskEndDate { get; set; }
        [DisplayName("Task Status")]
        [Required(ErrorMessage = "Task Status is required.")]
        public System.Guid TaskStatusId { get; set; }
        [DisplayName("User Story")]
        [Required(ErrorMessage = "User Story is required.")]
        public System.Guid UserStoryId { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime InsAt { get; set; }
        public string InsBy { get; set; }
        public System.DateTime UpdAt { get; set; }
        public string UpdBy { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManagerComment> ManagerComments { get; set; }
        public virtual TaskStatu TaskStatu { get; set; }
        public virtual UserStory UserStory { get; set; }
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            if (TaskEndDate <= TaskStartDate)
            {
                yield return new ValidationResult("EndDate must be greater than StartDate");
            }
        }
    }
}
